# Generated by Django 3.1.6 on 2021-02-15 12:39

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 15, 17, 39, 42, 384049), verbose_name='Дата'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='type',
            field=models.CharField(max_length=100, verbose_name='Тип'),
        ),
    ]
