# Generated by Django 3.1.6 on 2021-02-15 12:41

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_auto_20210215_1739'),
    ]

    operations = [
        migrations.AlterField(
            model_name='categories',
            name='parent_id',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='shop.categories', verbose_name='Категория'),
        ),
        migrations.AlterField(
            model_name='transactions',
            name='date',
            field=models.DateTimeField(default=datetime.datetime(2021, 2, 15, 17, 41, 36, 364023), verbose_name='Дата'),
        ),
    ]
